<?php

use Illuminate\Database\Seeder;

class FollowUpOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('follow_up_options')->insert([
            ['id' => 1, 'follow_up_question_id' => 1, "option" => "Monday"],
            ['id' => 2, 'follow_up_question_id' => 1, "option" => "Tuesday"],
            ['id' => 3, 'follow_up_question_id' => 1, "option" => "Wednesday"],
            ['id' => 4, 'follow_up_question_id' => 1, "option" => "Thursday"],
            ['id' => 5, 'follow_up_question_id' => 1, "option" => "Friday"],
            ['id' => 6, 'follow_up_question_id' => 2, "option" => "Business Information Systems"],
            ['id' => 7, 'follow_up_question_id' => 2, "option" => "Information Technology Management for Business (ITMB)"],
            ['id' => 8, 'follow_up_question_id' => 2, "option" => "Computer Science"],
            ['id' => 9, 'follow_up_question_id' => 2, "option" => "Computer Science and Mathematics"],
            ['id' => 10, 'follow_up_question_id' => 2, "option" => "Data Science"],
            ['id' => 11, 'follow_up_question_id' => 2, "option" => "Computer Security and Networks"],
            ['id' => 12, 'follow_up_question_id' => 2, "option" => "Computing"],
            ['id' => 13, 'follow_up_question_id' => 2, "option" => "Computing (Games Programming)"],
            ['id' => 14, 'follow_up_question_id' => 2, "option" => "Computing (Networking, Security and Forensics)"],
            ['id' => 15, 'follow_up_question_id' => 2, "option" => "Software Application Development"],
            ['id' => 16, 'follow_up_question_id' => 2, "option" => "Web Design and Development"],

            ['id' => 17, 'follow_up_question_id' => 3, "option" => "Business Information Systems"],
            ['id' => 18, 'follow_up_question_id' => 3, "option" => "Information Technology Management for Business (ITMB)"],
            ['id' => 19, 'follow_up_question_id' => 3, "option" => "Computer Science"],
            ['id' => 20, 'follow_up_question_id' => 3, "option" => "Computer Science and Mathematics"],
            ['id' => 21, 'follow_up_question_id' => 3, "option" => "Data Science"],
            ['id' => 22, 'follow_up_question_id' => 3, "option" => "Computer Security and Networks"],
            ['id' => 23, 'follow_up_question_id' => 3, "option" => "Computing"],
            ['id' => 24, 'follow_up_question_id' => 3, "option" => "Computing (Games Programming)"],
            ['id' => 25, 'follow_up_question_id' => 3, "option" => "Computing (Networking, Security and Forensics)"],
            ['id' => 26, 'follow_up_question_id' => 3, "option" => "Software Application Development"],
            ['id' => 27, 'follow_up_question_id' => 3, "option" => "Web Design and Development"],
            ['id' => 28, 'follow_up_question_id' => 4, "option" => "Edge Link Timetable"],
            ['id' => 29, 'follow_up_question_id' => 5, "option" => "Circuit App for iOS"],
            ['id' => 30, 'follow_up_question_id' => 5, "option" => "Circuit App for Android"],
            ['id' => 31, 'follow_up_question_id' => 6, "option" => "Eduroam (IT Services)"],
            ['id' => 32, 'follow_up_question_id' => 7, "option" => "Council Tax Exemption Certificate"],
            ['id' => 33, 'follow_up_question_id' => 8, "option" => "Parking Permits"],
            ['id' => 34, 'follow_up_question_id' => 9, "option" => "EHSU Societies"],
            ['id' => 35, 'follow_up_question_id' => 10, "option" => "SU Bar opening times"],
            ['id' => 36, 'follow_up_question_id' => 11, "option" => "Welcome Sunday"],
            ['id' => 37, 'follow_up_question_id' => 11, "option" => "Monday"],
            ['id' => 38, 'follow_up_question_id' => 11, "option" => "Tuesday"],
            ['id' => 39, 'follow_up_question_id' => 11, "option" => "Wednesday"],
            ['id' => 40, 'follow_up_question_id' => 11, "option" => "Thursday"],
            ['id' => 41, 'follow_up_question_id' => 11, "option" => "Friday"],
            ['id' => 42, 'follow_up_question_id' => 11, "option" => "Saturday"],
            ['id' => 43, 'follow_up_question_id' => 11, "option" => "Sunday"],
            ['id' => 44, 'follow_up_question_id' => 12, "option" => "Sages (The Hub)"],
            ['id' => 45, 'follow_up_question_id' => 12, "option" => "Grab and Go (The Hub)"],
            ['id' => 46, 'follow_up_question_id' => 12, "option" => "Cafe Rewind (Faculty of Health & Social Care)"],
            ['id' => 47, 'follow_up_question_id' => 12, "option" => "The Red Bar (The Arts Centre)"],
            ['id' => 48, 'follow_up_question_id' => 12, "option" => "Water's Edge (Faculty of Education)"],
            ['id' => 49, 'follow_up_question_id' => 12, "option" => "SU Bar"],
            ['id' => 50, 'follow_up_question_id' => 12, "option" => "Subway"],
            ['id' => 51, 'follow_up_question_id' => 13, "option" => "Department of Computer Science Facilities"],
            ['id' => 52, 'follow_up_question_id' => 14, "option" => "University Email"],
            ['id' => 53, 'follow_up_question_id' => 15, "option" => "Students' Homepage"],
            ['id' => 54, 'follow_up_question_id' => 16, "option" => "Learning Edge"],
            ['id' => 55, 'follow_up_question_id' => 17, "option" => "My FM"],
            ['id' => 56, 'follow_up_question_id' => 18, "option" => "Games Console Setup"],
            ['id' => 57, 'follow_up_question_id' => 19, "option" => "Learning Services"],
            ['id' => 58, 'follow_up_question_id' => 20, "option" => "Computer Availability"],
            ['id' => 59, 'follow_up_question_id' => 21, "option" => "Learning Services Live Chat"],
            ['id' => 60, 'follow_up_question_id' => 22, "option" => "CatalystEnquiries@edgehill.ac.uk"],
            ['id' => 61, 'follow_up_question_id' => 22, "option" => "Money Advice Website"],
            ['id' => 62, 'follow_up_question_id' => 23, "option" => "EHU Microsoft Office"],
            ['id' => 63, 'follow_up_question_id' => 24, "option" => "EHU Password Reset"],
            ['id' => 64, 'follow_up_question_id' => 25, "option" => "EHU Harvard Referencing"],
            ['id' => 65, 'follow_up_question_id' => 26, "option" => "GOV.UK Register to Vote"],
            ['id' => 66, 'follow_up_question_id' => 27, "option" => "Book a Study Room"],
            ['id' => 67, 'follow_up_question_id' => 28, "option" => "Changing Courses"],
            ['id' => 68, 'follow_up_question_id' => 28, "option" => "Leaving the University"],
            ['id' => 69, 'follow_up_question_id' => 29, "option" => "Scholarship Calculator"],
            ['id' => 70, 'follow_up_question_id' => 30, "option" => "Team Edge Hill"],
            ['id' => 71, 'follow_up_question_id' => 31, "option" => "Business Information Systems (MComp)"],
            ['id' => 72, 'follow_up_question_id' => 31, "option" => "Information Technology Management for Business (ITMB)"],
            ['id' => 73, 'follow_up_question_id' => 31, "option" => "Robotics and Artificial Intelligence"],
            ['id' => 74, 'follow_up_question_id' => 31, "option" => "Computer Science"],
            ['id' => 75, 'follow_up_question_id' => 31, "option" => "Computer Science and Mathematics"],
            ['id' => 76, 'follow_up_question_id' => 31, "option" => "Data Science"],
            ['id' => 77, 'follow_up_question_id' => 31, "option" => "Computer Security and Networks (MComp)"],
            ['id' => 78, 'follow_up_question_id' => 31, "option" => "Computing (BSc and MComp)"],
            ['id' => 79, 'follow_up_question_id' => 31, "option" => "Computing (Games Programming)"],
            ['id' => 80, 'follow_up_question_id' => 31, "option" => "Computing (Networking, Security and Forensics)"],
            ['id' => 81, 'follow_up_question_id' => 31, "option" => "Software Application Development (MComp)"],
            ['id' => 82, 'follow_up_question_id' => 31, "option" => "Software Engineering"],
            ['id' => 83, 'follow_up_question_id' => 31, "option" => "Web Design and Development (BSc and MComp)"],
            ['id' => 84, 'follow_up_question_id' => 32, "option" => "Learning Edge"],
        ]);
    }
}
