<?php

use Illuminate\Database\Seeder;

class KeywordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('keywords')->truncate();
        DB::table('keywords')->insert([
            ['id' => 1, 'keyword' => 'freshers'],
            ['id' => 2, 'keyword' => 'week'],
            ['id' => 3, 'keyword' => 'attend'],
            ['id' => 4, 'keyword' => 'event'],
            ['id' => 5, 'keyword' => 'induction'],
            ['id' => 6, 'keyword' => 'timetable'],
            ['id' => 7, 'keyword' => 'contact'],
            ['id' => 8, 'keyword' => 'going'],
            ['id' => 9, 'keyword' => 'be'],
            ['id' => 10, 'keyword' => 'absent'],
            ['id' => 11, 'keyword' => 'course'],
            ['id' => 12, 'keyword' => 'access'],
            ['id' => 13, 'keyword' => 'semester'],
            ['id' => 14, 'keyword' => 'download'],
            ['id' => 15, 'keyword' => 'leader'],
            ['id' => 16, 'keyword' => 'talk'],
            ['id' => 17, 'keyword' => 'enjoying'],
            ['id' => 18, 'keyword' => 'languages'],
            ['id' => 19, 'keyword' => 'session'],
            ['id' => 20, 'keyword' => 'staff'],
            ['id' => 21, 'keyword' => 'edge'],
            ['id' => 22, 'keyword' => 'link'],
            ['id' => 23, 'keyword' => 'bus'],
            ['id' => 24, 'keyword' => 'run'],
            ['id' => 25, 'keyword' => 'collect'],
            ['id' => 26, 'keyword' => 'post'],
            ['id' => 27, 'keyword' => 'time'],
            ['id' => 28, 'keyword' => 'launderette'],
            ['id' => 29, 'keyword' => 'open'],
            ['id' => 30, 'keyword' => 'close'],
            ['id' => 31, 'keyword' => 'pay'],
            ['id' => 32, 'keyword' => 'do'],
            ['id' => 33, 'keyword' => 'laundry'],
            ['id' => 34, 'keyword' => 'app'],
            ['id' => 35, 'keyword' => 'mccolls'],
            ['id' => 36, 'keyword' => 'having'],
            ['id' => 37, 'keyword' => 'trouble'],
            ['id' => 38, 'keyword' => 'connecting'],
            ['id' => 39, 'keyword' => 'eduroam'],
            ['id' => 40, 'keyword' => 'get'],
            ['id' => 41, 'keyword' => 'council'],
            ['id' => 42, 'keyword' => 'tax'],
            ['id' => 43, 'keyword' => 'exemption'],
            ['id' => 44, 'keyword' => 'certificate'],
            ['id' => 45, 'keyword' => 'loud'],
            ['id' => 46, 'keyword' => 'neighbours'],
            ['id' => 47, 'keyword' => 'excessive'],
            ['id' => 48, 'keyword' => 'noise'],
            ['id' => 49, 'keyword' => 'apply'],
            ['id' => 50, 'keyword' => 'parking'],
            ['id' => 51, 'keyword' => 'permit'],
            ['id' => 52, 'keyword' => 'are'],
            ['id' => 53, 'keyword' => 'societies'],
            ['id' => 54, 'keyword' => 'join'],
            ['id' => 55, 'keyword' => 'students'],
            ['id' => 56, 'keyword' => 'union'],
            ['id' => 57, 'keyword' => 'bar'],
            ['id' => 58, 'keyword' => 'su'],
            ['id' => 59, 'keyword' => 'events'],
            ['id' => 60, 'keyword' => 'running'],
            ['id' => 61, 'keyword' => 'something'],
            ['id' => 62, 'keyword' => 'eat'],
            ['id' => 63, 'keyword' => 'campus'],
            ['id' => 64, 'keyword' => 'head'],
            ['id' => 65, 'keyword' => 'department'],
            ['id' => 66, 'keyword' => 'director'],
            ['id' => 67, 'keyword' => 'undergraduate'],
            ['id' => 68, 'keyword' => 'studies'],
            ['id' => 69, 'keyword' => 'facilities'],
            ['id' => 70, 'keyword' => 'provide'],
            ['id' => 71, 'keyword' => 'email'],
            ['id' => 72, 'keyword' => 'account'],
            ['id' => 73, 'keyword' => 'university'],
            ['id' => 74, 'keyword' => 'services'],
            ['id' => 75, 'keyword' => 'blackboard'],
            ['id' => 76, 'keyword' => 'learning'],
            ['id' => 77, 'keyword' => 'room'],
            ['id' => 78, 'keyword' => 'broken'],
            ['id' => 79, 'keyword' => 'repaired'],
            ['id' => 80, 'keyword' => 'connect'],
            ['id' => 81, 'keyword' => 'playstation'],
            ['id' => 82, 'keyword' => 'ps'],
            ['id' => 83, 'keyword' => 'xbox'],
            ['id' => 84, 'keyword' => 'internet'],
            ['id' => 85, 'keyword' => 'find'],
            ['id' => 86, 'keyword' => 'book'],
            ['id' => 87, 'keyword' => 'available'],
            ['id' => 88, 'keyword' => 'library'],
            ['id' => 89, 'keyword' => 'check'],
            ['id' => 90, 'keyword' => 'computer'],
            ['id' => 91, 'keyword' => 'availability'],
            ['id' => 92, 'keyword' => 'catalyst'],
            ['id' => 93, 'keyword' => 'struggling'],
            ['id' => 94, 'keyword' => 'money'],
            ['id' => 95, 'keyword' => 'microsoft'],
            ['id' => 96, 'keyword' => 'office'],
            ['id' => 97, 'keyword' => 'reset'],
            ['id' => 98, 'keyword' => 'password'],
            ['id' => 99, 'keyword' => 'referencing'],
            ['id' => 100, 'keyword' => 'work'],
            ['id' => 101, 'keyword' => 'register'],
            ['id' => 102, 'keyword' => 'vote'],
            ['id' => 103, 'keyword' => 'individual'],
            ['id' => 104, 'keyword' => 'group'],
            ['id' => 105, 'keyword' => 'study'],
            ['id' => 106, 'keyword' => 'change'],
            ['id' => 107, 'keyword' => 'leave'],
            ['id' => 108, 'keyword' => 'bursary'],
            ['id' => 109, 'keyword' => 'scholarship'],
            ['id' => 110, 'keyword' => 'sports'],
            ['id' => 111, 'keyword' => 'team'],
            ['id' => 112, 'keyword' => 'which'],
            ['id' => 113, 'keyword' => 'modules'],
            ['id' => 114, 'keyword' => 'studying'],
            ['id' => 115, 'keyword' => 'year'],
            ['id' => 116, 'keyword' => 'anything'],
            ['id' => 117, 'keyword' => 'buy'],
            ['id' => 118, 'keyword' => 'personal'],
            ['id' => 119, 'keyword' => 'tutor'],
        ]);
    }
}
