<?php

use Illuminate\Database\Seeder;

class KeywordQuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('keyword_question')->truncate();
        DB::table('keyword_question')->insert([
            ['id' => 1, 'question_id' => 1, 'keyword_id' => 1],
            ['id' => 2, 'question_id' => 1, 'keyword_id' => 2],
            ['id' => 3, 'question_id' => 2, 'keyword_id' => 3],
            ['id' => 4, 'question_id' => 2, 'keyword_id' => 4],
            ['id' => 5, 'question_id' => 2, 'keyword_id' => 5],
            ['id' => 6, 'question_id' => 2, 'keyword_id' => 6],
            ['id' => 7, 'question_id' => 3, 'keyword_id' => 7],
            ['id' => 8, 'question_id' => 3, 'keyword_id' => 8],
            ['id' => 9, 'question_id' => 3, 'keyword_id' => 9],
            ['id' => 10, 'question_id' => 3, 'keyword_id' => 10],
            ['id' => 11, 'question_id' => 4, 'keyword_id' => 11],
            ['id' => 12, 'question_id' => 4, 'keyword_id' => 6],
            ['id' => 13, 'question_id' => 4, 'keyword_id' => 1],
            ['id' => 14, 'question_id' => 4, 'keyword_id' => 2],
            ['id' => 15, 'question_id' => 5, 'keyword_id' => 11],
            ['id' => 16, 'question_id' => 5, 'keyword_id' => 6],
            ['id' => 17, 'question_id' => 5, 'keyword_id' => 12],
            ['id' => 18, 'question_id' => 6, 'keyword_id' => 13],
            ['id' => 19, 'question_id' => 6, 'keyword_id' => 5],
            ['id' => 20, 'question_id' => 6, 'keyword_id' => 6],
            ['id' => 21, 'question_id' => 7, 'keyword_id' => 14],
            ['id' => 22, 'question_id' => 7, 'keyword_id' => 15],
            ['id' => 23, 'question_id' => 8, 'keyword_id' => 16],
            ['id' => 24, 'question_id' => 8, 'keyword_id' => 17],
            ['id' => 25, 'question_id' => 8, 'keyword_id' => 14],
            ['id' => 26, 'question_id' => 9, 'keyword_id' => 3],
            ['id' => 27, 'question_id' => 9, 'keyword_id' => 18],
            ['id' => 28, 'question_id' => 9, 'keyword_id' => 19],
            ['id' => 29, 'question_id' => 10, 'keyword_id' => 7],
            ['id' => 30, 'question_id' => 10, 'keyword_id' => 20],
            ['id' => 31, 'question_id' => 11, 'keyword_id' => 21],
            ['id' => 32, 'question_id' => 11, 'keyword_id' => 22],
            ['id' => 33, 'question_id' => 11, 'keyword_id' => 23],
            ['id' => 34, 'question_id' => 11, 'keyword_id' => 24],
            ['id' => 35, 'question_id' => 12, 'keyword_id' => 21],
            ['id' => 36, 'question_id' => 12, 'keyword_id' => 22],
            ['id' => 37, 'question_id' => 12, 'keyword_id' => 6],
            ['id' => 38, 'question_id' => 13, 'keyword_id' => 25],
            ['id' => 39, 'question_id' => 13, 'keyword_id' => 26],
            ['id' => 40, 'question_id' => 14, 'keyword_id' => 27],
            ['id' => 41, 'question_id' => 14, 'keyword_id' => 28],
            ['id' => 42, 'question_id' => 14, 'keyword_id' => 29],
            ['id' => 43, 'question_id' => 14, 'keyword_id' => 30],
            ['id' => 44, 'question_id' => 15, 'keyword_id' => 31],
            ['id' => 45, 'question_id' => 15, 'keyword_id' => 32],
            ['id' => 46, 'question_id' => 15, 'keyword_id' => 33],
            ['id' => 47, 'question_id' => 16, 'keyword_id' => 13],
            ['id' => 48, 'question_id' => 16, 'keyword_id' => 34],
            ['id' => 49, 'question_id' => 16, 'keyword_id' => 33],
            ['id' => 50, 'question_id' => 17, 'keyword_id' => 27],
            ['id' => 51, 'question_id' => 17, 'keyword_id' => 35],
            ['id' => 52, 'question_id' => 17, 'keyword_id' => 29],
            ['id' => 53, 'question_id' => 17, 'keyword_id' => 30],
            ['id' => 54, 'question_id' => 18, 'keyword_id' => 36],
            ['id' => 55, 'question_id' => 18, 'keyword_id' => 37],
            ['id' => 56, 'question_id' => 18, 'keyword_id' => 38],
            ['id' => 57, 'question_id' => 18, 'keyword_id' => 39],
            ['id' => 58, 'question_id' => 18, 'keyword_id' => 7],
            ['id' => 59, 'question_id' => 19, 'keyword_id' => 40],
            ['id' => 60, 'question_id' => 19, 'keyword_id' => 41],
            ['id' => 61, 'question_id' => 19, 'keyword_id' => 42],
            ['id' => 62, 'question_id' => 19, 'keyword_id' => 43],
            ['id' => 63, 'question_id' => 19, 'keyword_id' => 44],
            ['id' => 64, 'question_id' => 20, 'keyword_id' => 7],
            ['id' => 65, 'question_id' => 20, 'keyword_id' => 45],
            ['id' => 66, 'question_id' => 20, 'keyword_id' => 46],
            ['id' => 67, 'question_id' => 20, 'keyword_id' => 47],
            ['id' => 68, 'question_id' => 20, 'keyword_id' => 48],
            ['id' => 69, 'question_id' => 21, 'keyword_id' => 49],
            ['id' => 70, 'question_id' => 21, 'keyword_id' => 50],
            ['id' => 71, 'question_id' => 21, 'keyword_id' => 51],
            ['id' => 72, 'question_id' => 22, 'keyword_id' => 52],
            ['id' => 73, 'question_id' => 22, 'keyword_id' => 53],
            ['id' => 74, 'question_id' => 22, 'keyword_id' => 54],
            ['id' => 75, 'question_id' => 23, 'keyword_id' => 27],
            ['id' => 76, 'question_id' => 23, 'keyword_id' => 55],
            ['id' => 77, 'question_id' => 23, 'keyword_id' => 56],
            ['id' => 78, 'question_id' => 23, 'keyword_id' => 57],
            ['id' => 79, 'question_id' => 23, 'keyword_id' => 58],
            ['id' => 80, 'question_id' => 23, 'keyword_id' => 30],
            ['id' => 81, 'question_id' => 24, 'keyword_id' => 59],
            ['id' => 82, 'question_id' => 24, 'keyword_id' => 55],
            ['id' => 83, 'question_id' => 24, 'keyword_id' => 56],
            ['id' => 84, 'question_id' => 24, 'keyword_id' => 58],
            ['id' => 85, 'question_id' => 24, 'keyword_id' => 60],
            ['id' => 86, 'question_id' => 24, 'keyword_id' => 1],
            ['id' => 87, 'question_id' => 24, 'keyword_id' => 2],
            ['id' => 88, 'question_id' => 25, 'keyword_id' => 40],
            ['id' => 89, 'question_id' => 25, 'keyword_id' => 61],
            ['id' => 90, 'question_id' => 25, 'keyword_id' => 62],
            ['id' => 91, 'question_id' => 25, 'keyword_id' => 63],
            ['id' => 92, 'question_id' => 26, 'keyword_id' => 64],
            ['id' => 93, 'question_id' => 26, 'keyword_id' => 65],
            ['id' => 94, 'question_id' => 27, 'keyword_id' => 66],
            ['id' => 95, 'question_id' => 27, 'keyword_id' => 67],
            ['id' => 96, 'question_id' => 27, 'keyword_id' => 68],
            ['id' => 97, 'question_id' => 28, 'keyword_id' => 69],
            ['id' => 98, 'question_id' => 28, 'keyword_id' => 65],
            ['id' => 99, 'question_id' => 28, 'keyword_id' => 70],
            ['id' => 100, 'question_id' => 29, 'keyword_id' => 11],
            ['id' => 101, 'question_id' => 29, 'keyword_id' => 71],
            ['id' => 102, 'question_id' => 29, 'keyword_id' => 72],
            ['id' => 103, 'question_id' => 30, 'keyword_id' => 11],
            ['id' => 104, 'question_id' => 30, 'keyword_id' => 73],
            ['id' => 105, 'question_id' => 30, 'keyword_id' => 74],
            ['id' => 106, 'question_id' => 31, 'keyword_id' => 11],
            ['id' => 107, 'question_id' => 31, 'keyword_id' => 75],
            ['id' => 108, 'question_id' => 31, 'keyword_id' => 76],
            ['id' => 109, 'question_id' => 31, 'keyword_id' => 21],
            ['id' => 110, 'question_id' => 32, 'keyword_id' => 61],
            ['id' => 111, 'question_id' => 32, 'keyword_id' => 77],
            ['id' => 112, 'question_id' => 32, 'keyword_id' => 78],
            ['id' => 113, 'question_id' => 32, 'keyword_id' => 40],
            ['id' => 114, 'question_id' => 32, 'keyword_id' => 79],
            ['id' => 115, 'question_id' => 33, 'keyword_id' => 80],
            ['id' => 116, 'question_id' => 33, 'keyword_id' => 81],
            ['id' => 117, 'question_id' => 33, 'keyword_id' => 82],
            ['id' => 118, 'question_id' => 33, 'keyword_id' => 83],
            ['id' => 119, 'question_id' => 33, 'keyword_id' => 84],
            ['id' => 120, 'question_id' => 34, 'keyword_id' => 85],
            ['id' => 121, 'question_id' => 34, 'keyword_id' => 86],
            ['id' => 122, 'question_id' => 34, 'keyword_id' => 87],
            ['id' => 123, 'question_id' => 34, 'keyword_id' => 88],
            ['id' => 124, 'question_id' => 35, 'keyword_id' => 89],
            ['id' => 125, 'question_id' => 35, 'keyword_id' => 90],
            ['id' => 126, 'question_id' => 35, 'keyword_id' => 91],
            ['id' => 127, 'question_id' => 35, 'keyword_id' => 92],
            ['id' => 128, 'question_id' => 36, 'keyword_id' => 7],
            ['id' => 129, 'question_id' => 36, 'keyword_id' => 76],
            ['id' => 130, 'question_id' => 36, 'keyword_id' => 74],
            ['id' => 131, 'question_id' => 37, 'keyword_id' => 93],
            ['id' => 132, 'question_id' => 37, 'keyword_id' => 94],
            ['id' => 133, 'question_id' => 37, 'keyword_id' => 16],
            ['id' => 134, 'question_id' => 38, 'keyword_id' => 73],
            ['id' => 135, 'question_id' => 38, 'keyword_id' => 95],
            ['id' => 136, 'question_id' => 38, 'keyword_id' => 96],
            ['id' => 137, 'question_id' => 39, 'keyword_id' => 97],
            ['id' => 138, 'question_id' => 39, 'keyword_id' => 98],
            ['id' => 139, 'question_id' => 40, 'keyword_id' => 99],
            ['id' => 140, 'question_id' => 40, 'keyword_id' => 100],
            ['id' => 141, 'question_id' => 41, 'keyword_id' => 101],
            ['id' => 142, 'question_id' => 41, 'keyword_id' => 102],
            ['id' => 143, 'question_id' => 42, 'keyword_id' => 86],
            ['id' => 144, 'question_id' => 42, 'keyword_id' => 103],
            ['id' => 145, 'question_id' => 42, 'keyword_id' => 104],
            ['id' => 146, 'question_id' => 42, 'keyword_id' => 105],
            ['id' => 147, 'question_id' => 42, 'keyword_id' => 77],
            ['id' => 148, 'question_id' => 42, 'keyword_id' => 88],
            ['id' => 149, 'question_id' => 43, 'keyword_id' => 16],
            ['id' => 150, 'question_id' => 43, 'keyword_id' => 106],
            ['id' => 151, 'question_id' => 43, 'keyword_id' => 14],
            ['id' => 152, 'question_id' => 43, 'keyword_id' => 107],
            ['id' => 153, 'question_id' => 43, 'keyword_id' => 73],
            ['id' => 154, 'question_id' => 44, 'keyword_id' => 40],
            ['id' => 155, 'question_id' => 44, 'keyword_id' => 108],
            ['id' => 156, 'question_id' => 44, 'keyword_id' => 109],
            ['id' => 157, 'question_id' => 45, 'keyword_id' => 54],
            ['id' => 158, 'question_id' => 45, 'keyword_id' => 110],
            ['id' => 159, 'question_id' => 45, 'keyword_id' => 111],
            ['id' => 160, 'question_id' => 46, 'keyword_id' => 112],
            ['id' => 161, 'question_id' => 46, 'keyword_id' => 113],
            ['id' => 162, 'question_id' => 46, 'keyword_id' => 9],
            ['id' => 163, 'question_id' => 46, 'keyword_id' => 114],
            ['id' => 164, 'question_id' => 46, 'keyword_id' => 115],
            ['id' => 165, 'question_id' => 47, 'keyword_id' => 116],
            ['id' => 166, 'question_id' => 47, 'keyword_id' => 117],
            ['id' => 167, 'question_id' => 47, 'keyword_id' => 32],
            ['id' => 168, 'question_id' => 47, 'keyword_id' => 14],
            ['id' => 169, 'question_id' => 48, 'keyword_id' => 118],
            ['id' => 170, 'question_id' => 48, 'keyword_id' => 119],
        ]);
    }
}
